# Generated by Django 2.2.5 on 2019-12-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentlocation',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apartmentlocation',
            name='city',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apartmentlocation',
            name='district',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apartmentlocation',
            name='notes',
            field=models.TextField(),
        ),
    ]
