# Generated by Django 2.2.5 on 2019-12-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_apartment_apartment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_type', to='common_models.ApartmentType', to_field='type'),
        ),
    ]
