# Generated by Django 2.2.7 on 2019-12-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStaff',
            new_name='StaffManager',
        ),
    ]
