# Generated by Django 2.2.5 on 2019-12-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0002_apartment_apartment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('started_date', models.DateField()),
                ('ended_date', models.DateField()),
                ('type', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('cancel', 'cancel'), ('done', 'done')], default='pending', max_length=50)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('apartment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment_request', to='apartment.Apartment')),
            ],
        ),
    ]
