# Generated by Django 2.2.5 on 2019-12-29 09:47

from django.db import migrations, models
import lvtn_apps.utils.method_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('send_all', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=lvtn_apps.utils.method_utils.generate_name_image)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
