# Generated by Django 2.2.7 on 2019-12-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191229_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='birth_day'),
        ),
    ]
