# Generated by Django 2.2.7 on 2019-12-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_birth_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_day',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
