# Generated by Django 2.2.7 on 2019-12-29 08:48

import django.core.validators
from django.db import migrations, models
import lvtn_apps.utils.method_utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191229_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=lvtn_apps.utils.method_utils.generate_name_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'svg'])]),
        ),
    ]
